Documentation:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

SymbolName:
  Enabled: false

Encoding:
  Enabled: false

StringLiterals:
  Enabled: false

Void:
  Enabled: false

inherit_from: rubocop-todo.yml
